version = 1
SPDX-PackageName = "Model Game Development Standard"
SPDX-PackageDownloadLocation = "https://github.com/gmackie/mgds"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 MGDS contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/*.md", "**/*.html", "LICENSE-DOCS"]
precedence = "override"
SPDX-FileCopyrightText = "2026 MGDS contributors"
SPDX-License-Identifier = "CC-BY-4.0"
